### ISSUE TITLE
assemblyJarName in assembly := "scalada-learning-assembly.jar"

### ISSUE THREAD

**Issue by nellaivijay** [arunma/ScalaDataAnalysisCookbook#1]
While imporitng the project from Intelljidea, its showing up the below error message
Error while importing SBT project: 
C:\Users\ramdov\IdeaProjects\ScalaDataAnalysisCookbook\chapter6-scalingup\build.sbt:18: error: not found: value assemblyJarName
assemblyJarName in assembly := "scalada-learning-assembly.jar"
^
[error] Type error in expression

**Comment by arunma** [comment]
Sorry for the trouble and thanks for raising this issue Vijay.  The issue is because you are trying to import the code from its root (which I should have tested before checking in).  I have added the assembly and the avro plugin to the root/project/assembly.sbt through the [checkin](https://github.com/arunma/ScalaDataAnalysisCookbook/commit/32a8d24da9082f081c4cf704a2ec89e8d298ccdd) I just made.  You should be able to import just fine now.

However, I personally suggest you to import the project at the project level than at the SBT level so that IntelliJ picks up source and test roots correctly.

**Comment by nellaivijay** [comment]
thanks, let me check now
